export const browserCoreExamples = [
  "talon browser status",
  "talon browser start",
  "talon browser stop",
  "talon browser tabs",
  "talon browser open https://example.com",
  "talon browser focus abcd1234",
  "talon browser close abcd1234",
  "talon browser screenshot",
  "talon browser screenshot --full-page",
  "talon browser screenshot --ref 12",
  "talon browser snapshot",
  "talon browser snapshot --format aria --limit 200",
  "talon browser snapshot --efficient",
  "talon browser snapshot --labels",
];

export const browserActionExamples = [
  "talon browser navigate https://example.com",
  "talon browser resize 1280 720",
  "talon browser click 12 --double",
  'talon browser type 23 "hello" --submit',
  "talon browser press Enter",
  "talon browser hover 44",
  "talon browser drag 10 11",
  "talon browser select 9 OptionA OptionB",
  "talon browser upload /tmp/file.pdf",
  'talon browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "talon browser dialog --accept",
  'talon browser wait --text "Done"',
  "talon browser evaluate --fn '(el) => el.textContent' --ref 7",
  "talon browser console --level error",
  "talon browser pdf",
];
