export const DEFAULT_BROWSER_EVALUATE_ENABLED = false;
export const DEFAULT_TALON_BROWSER_COLOR = "#000000";
export const DEFAULT_TALON_BROWSER_PROFILE_NAME = "default";
export const DEFAULT_AI_SNAPSHOT_MAX_CHARS = 10000;
